# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

submodules:
  include:
    - documentation/_dependencies/breathe

# Optionally set the version of Python and requirements required to build your docs
python:
   version: 3.7
   install:
    - method: setuptools
      path: documentation/_dependencies/breathe
      
# Build documentation in the documentation/ directory with Sphinx
sphinx:
   configuration: documentation/conf.py